# Generated by Django 3.0.6 on 2020-05-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.IntegerField(unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('count_products', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('body', models.TextField(max_length=1000)),
                ('category', models.ManyToManyField(blank=True, related_name='item', to='home.CategoryModel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductModel')),
            ],
        ),
    ]
