# Generated by Django 3.0.6 on 2020-05-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200520_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemModel',
            new_name='ProductDescribeModel',
        ),
    ]
