# Generated by Django 3.0.6 on 2020-05-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_basketmodel_product_describe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketmodel',
            name='product_describe',
        ),
    ]
