# Generated by Django 3.0.6 on 2020-05-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200518_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(related_name='item', to='home.Category'),
        ),
    ]
