# Generated by Django 3.0.6 on 2020-05-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_basketmodel_product_describe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketmodel',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='basketmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
