# Generated by Django 3.0.6 on 2020-05-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200521_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='product_describe',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='home.ProductDescribeModel'),
        ),
    ]
