# Generated by Django 3.0.6 on 2020-05-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_basketmodel_product_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescribemodel',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='product_describe', to='home.CategoryModel'),
        ),
    ]
