# Generated by Django 3.0.6 on 2020-05-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_item_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemModel',
        ),
    ]
