# Generated by Django 3.0.6 on 2020-06-03 00:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200523_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescribemodel',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 6, 3, 0, 26, 35, 891930, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='count_products',
            field=models.IntegerField(default=0),
        ),
    ]
