# Generated by Django 3.0.6 on 2020-06-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.CharField(max_length=70),
        ),
    ]
