# Generated by Django 3.0.6 on 2020-06-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200604_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
