# Generated by Django 3.0.6 on 2020-06-04 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_productordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productordermodel',
            name='order',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='home.OrderModel'),
        ),
        migrations.AlterField(
            model_name='productordermodel',
            name='product',
            field=models.IntegerField(default=0),
        ),
    ]
