# Generated by Django 3.0.6 on 2020-06-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200604_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productordermodel',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.OrderModel'),
        ),
    ]
