# Generated by Django 3.0.6 on 2020-06-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200605_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productordermodel',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='home.ProductModel'),
        ),
    ]
