# Generated by Django 3.0.6 on 2020-06-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_ratingmodel_usermarkmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.ProductDescribeModel'),
        ),
    ]
