# Generated by Django 3.0.6 on 2020-06-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200608_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='voites',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='user_rating',
            field=models.IntegerField(),
        ),
    ]
