# Generated by Django 3.0.6 on 2020-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20200608_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonimusModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
