# Generated by Django 3.0.6 on 2020-06-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_anonimusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermarkmodel',
            name='token',
            field=models.IntegerField(),
        ),
    ]
