# Generated by Django 3.0.6 on 2020-06-12 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200609_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductDescribeModel')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='home.RatingModel')),
            ],
        ),
        migrations.DeleteModel(
            name='AnonimusModel',
        ),
        migrations.DeleteModel(
            name='UserMarkModel',
        ),
    ]
