# Generated by Django 3.0.6 on 2020-06-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200612_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingmodel',
            old_name='user_rating',
            new_name='rating',
        ),
    ]
