# Generated by Django 3.0.6 on 2020-06-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200612_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescribemodel',
            name='popular',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='home.ProductDescribeModel'),
        ),
    ]
