# Generated by Django 3.0.6 on 2020-06-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200613_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
