# Generated by Django 3.0.6 on 2020-06-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20200614_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescribemodel',
            name='tmp_count',
            field=models.IntegerField(default=1),
        ),
    ]
