# Generated by Django 3.0.6 on 2020-06-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20200615_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
