# Generated by Django 3.0.6 on 2020-06-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_couponmodel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='value',
            field=models.FloatField(default=1),
        ),
    ]
