# Generated by Django 3.0.6 on 2020-06-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20200615_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='adress',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='first_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='last_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='surname',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
