# Generated by Django 3.0.6 on 2020-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20200616_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='adress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phone_number',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
