# Generated by Django 3.0.6 on 2020-06-16 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0035_auto_20200616_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketmodel',
            name='count',
        ),
        migrations.RemoveField(
            model_name='basketmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='basketmodel',
            name='product_describe',
        ),
        migrations.AddField(
            model_name='basketmodel',
            name='sum_in_basket',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductBasketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.ProductModel')),
                ('product_basket', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.BasketModel')),
                ('product_describe', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='home.ProductDescribeModel')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
